# Generated by Django 3.0.5 on 2020-05-24 14:08

import star.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(default='', max_length=32)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('celebrity', models.CharField(choices=[('People', 'People'), ('Model', 'Model'), ('Actor-Actress', 'Actor Actress'), ('Artist', 'Artist'), ('Athlete', 'Athlete'), ('Businessman', 'Businessman'), ('Politician', 'Politician'), ('Scientist', 'Scientist')], max_length=32)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stars_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StarPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=star.models.StarPhoto.directory)),
                ('star', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='star.Star')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='star.Star')),
            ],
        ),
    ]
