# Generated by Django 3.1.3 on 2020-11-14 15:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201026_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
    ]
